### PR TITLE
Added Dutch Translations

### PR DESCRIPTION
**Pull request by DeveloperBoy**
Hello there!

I've translated the plugin to Dutch for you. It will be nice if you add it to the plugin. I'm dutch myself and I want to use the Dutch translations. ;)

Thanks in advance!

Regards,

Stijn

### CODE REVIEW

**Comment by DeveloperBoy** [comment]
I see I forgot the src/assets/negativity/nl_NL.yml file. I will add that soon. ;)

**Comment by Elikill58** [comment]
Oh, thanks you !
Just, it's de_DE or nl_NL the id of your language ?
Don't add both because the plugin will search de_DE.yml and nl_NL.yml xD

**Comment by DeveloperBoy** [comment]
> Oh, thanks you !
> Just, it's de_DE or nl_NL the id of your language ?
> Don't add both because the plugin will search de_DE.yml and nl_NL.yml xD

No, it's nl_NL, but because you forget to add de_DE with the latest update, I've added it for you. I will add the missing file in 5 minutes.

**Comment by Elikill58** [comment]
Oh, you right ! Thanks you !
No problem, i will merge after adding the missing file :)

**Comment by DeveloperBoy** [comment]
Done. ;)

**Comment by Elikill58** [comment]
Done too !

**Pull request merged**
