### PR TITLE
Added Indonesian language

### PR DESCRIPTION
**Pull request by dave9123**

### CODE REVIEW

**Comment by dave9123** [comment]
@Elikill58

**Comment by Elikill58** [comment]
Can you translate all 3 files in the same pull request ?

**Comment by dave9123** [comment]
Sure

**Comment by Elikill58** [comment]
Sorry for late, but you forget to translate this file: https://github.com/Elikill58/Negativity/blob/v2/common/resources/assets/negativity/Negativity_en_US.properties

**Comment by dave9123** [comment]
Oh yeah, sorry I forgot about that

**Comment by dave9123** [comment]
Fixed grammar for NegativityProxy and done with Negativity one

**Pull request merged**
