### PR TITLE
Translate Japanese

### PR DESCRIPTION
**Pull request by RamuneRemonedo**
I translated from English to Japanese.

### CODE REVIEW

**Comment by Elikill58** [comment]
Thanks you for this. Can you also translate the "CheatHover" and "NegativityProxy" files ?

**Comment by RamuneRemonedo** [comment]
oh sorry, I'll upload them.

**Comment by RamuneRemonedo** [comment]
I uploaded. Please check.

**Comment by Elikill58** [comment]
Sorry for the time. Perfect, thanks you :)

**Pull request merged**
